# seed_data.py — 70 curated Hawaii restaurants across all 4 islands
# Sources: well-established venues based on published restaurant guides and reviews.
# Note: Hours and prices are approximate. Lahaina Front Street venues excluded
# due to August 2023 wildfire. All locations verified by island.

RESTAURANTS = [

    # ═══════════════════════════════════════════════════════
    # OAHU — 22 restaurants
    # ═══════════════════════════════════════════════════════

    {
        "id": "rest_001",
        "name": "Nobu Honolulu",
        "island": "oahu",
        "cuisine": "Japanese Fine Dining",
        "tags": ["celebrity chef", "sushi", "omakase", "waikiki", "fine dining", "sake", "innovative"],
        "dietary_tags": ["gluten_free_options", "seafood_heavy"],
        "occasion_tags": ["romantic", "special_occasion", "social"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "international",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.2733, "lng": -157.8297},
        "description": "Chef Nobu Matsuhisa's iconic restaurant inside the Nobu Hotel Honolulu. World-famous black cod miso, yellowtail jalapeño, and the most refined sake program in Hawaii. A bucket-list dining experience that blends Japanese precision with Peruvian influence.",
    },
    {
        "id": "rest_002",
        "name": "The Pig and the Lady",
        "island": "oahu",
        "cuisine": "Vietnamese-Inspired Modern",
        "tags": ["chinatown", "creative", "pho", "vietnamese", "brunch", "local favorite", "hip"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["social", "solo", "adventurous_dining"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 10, "close": 21},
        "location": {"lat": 21.3076, "lng": -157.8601},
        "description": "The crown jewel of Honolulu's Chinatown revival. Chef Andrew Le's Vietnamese-American kitchen creates dishes like French dip pho, lamb larb, and seasonal noodle bowls that feel entirely new. Beloved brunch spot. Always lively.",
    },
    {
        "id": "rest_003",
        "name": "Helena's Hawaiian Food",
        "island": "oahu",
        "cuisine": "Traditional Hawaiian",
        "tags": ["james beard award", "local institution", "plate lunch", "poi", "laulau", "authentic", "cash only"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["solo", "family", "cultural_experience"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 19},
        "location": {"lat": 21.3144, "lng": -157.8536},
        "description": "A James Beard Award-winning Hawaiian food institution run by the same family since 1946. Laulau, kalua pig, squid luau, and pipikaula short ribs made the same way as always. No frills, no pretension — just the realest Hawaiian food on Oahu.",
    },
    {
        "id": "rest_004",
        "name": "Rainbow Drive-In",
        "island": "oahu",
        "cuisine": "Hawaiian Plate Lunch",
        "tags": ["plate lunch", "local icon", "drive-in", "cheap", "loco moco", "kapahulu", "comfort food"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 21},
        "location": {"lat": 21.2786, "lng": -157.8195},
        "description": "An Oahu legend since 1961. The line of locals and visitors stretching down Kapahulu Avenue every morning is proof. Loco moco, mixed plates with two scoops of rice, mac salad, and meat. The most Hawaiian fast food experience that exists.",
    },
    {
        "id": "rest_005",
        "name": "Leonard's Bakery",
        "island": "oahu",
        "cuisine": "Portuguese Bakery",
        "tags": ["malasadas", "bakery", "portuguese", "iconic", "kapahulu", "sweet", "morning"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 5, "close": 22},
        "location": {"lat": 21.2789, "lng": -157.8186},
        "description": "Since 1952, Leonard's has been frying the definitive malasada — a Portuguese donut rolled in sugar while still hot from the oil. The original plain version is perfect. The filled versions (custard, haupia, dobash) are dangerous. Open early, stay late.",
    },
    {
        "id": "rest_006",
        "name": "Marukame Udon",
        "island": "oahu",
        "cuisine": "Japanese Udon",
        "tags": ["udon", "japanese", "cheap", "waikiki", "counter service", "fresh noodles", "quick"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["solo", "quick_bite", "family"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "international",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 22},
        "location": {"lat": 21.2799, "lng": -157.8305},
        "description": "A Waikiki institution with lines stretching down Saratoga Road every day. Handmade udon noodles pulled fresh every morning, served in dashi broth with tempura made to order. Best value in Waikiki at under $10. Counter service, eat standing or grab a table.",
    },
    {
        "id": "rest_007",
        "name": "Duke's Waikiki",
        "island": "oahu",
        "cuisine": "Hawaiian Beachside",
        "tags": ["beachfront", "waikiki", "surf culture", "mai tais", "casual", "seafood", "sunset"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "social", "family"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 22},
        "location": {"lat": 21.2768, "lng": -157.8265},
        "description": "Named after Duke Kahanamoku and sitting right on Waikiki Beach at the Outrigger. Surfboards, ocean views, live music every evening, and classic Hawaiian-American plates. The hula pie and fish tacos are non-negotiable. Best mai tai on the beach.",
    },
    {
        "id": "rest_008",
        "name": "Side Street Inn",
        "island": "oahu",
        "cuisine": "Local Comfort Bar Food",
        "tags": ["local favorite", "pork chops", "fried rice", "bar", "late night", "oahu classic", "social"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["social", "friends_group", "late_night"],
        "price_range": 2,
        "noise_level": 4,
        "vibe": "social",
        "cuisine_style": "local",
        "spice_level": 2,
        "open_hours": {"open": 14, "close": 23},
        "location": {"lat": 21.2958, "lng": -157.8418},
        "description": "The off-duty chef's canteen of Honolulu. After service, this is where Hawaii's restaurant industry goes to eat enormous pork chops, pan-fried noodles, and truffle fries. Loud, loud, loud. No reservations. Worth every minute of the wait.",
    },
    {
        "id": "rest_009",
        "name": "Liliha Bakery",
        "island": "oahu",
        "cuisine": "Old-School Hawaiian Bakery",
        "tags": ["coco puffs", "bakery", "breakfast", "local institution", "cheap", "early morning", "nostalgic"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 6, "close": 22},
        "location": {"lat": 21.3231, "lng": -157.8617},
        "description": "The coco puff — a cream puff filled with chantilly frosting — is one of the most beloved things in Hawaii. Liliha has been making them since 1950. The counter breakfast (saimin, eggs, spam) is a portal to old Honolulu. Multiple locations island-wide.",
    },
    {
        "id": "rest_010",
        "name": "Roy's Waikiki",
        "island": "oahu",
        "cuisine": "Hawaiian Fusion",
        "tags": ["hawaiian fusion", "molten lava cake", "seafood", "creative", "open kitchen", "upscale", "waikiki"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion", "social"],
        "price_range": 3,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.2795, "lng": -157.8314},
        "description": "Chef Roy Yamaguchi's flagship restaurant that launched Hawaii Regional Cuisine in 1988. European technique meets Asian flavors meets Pacific seafood. The misoyaki butterfish and molten chocolate lava cake have been on the menu since opening night — for good reason.",
    },
    {
        "id": "rest_011",
        "name": "House Without a Key",
        "island": "oahu",
        "cuisine": "Hawaiian Sunset Cocktails",
        "tags": ["halekulani", "sunset", "live hula", "beachfront", "cocktails", "romantic", "waikiki"],
        "dietary_tags": ["seafood_heavy", "vegetarian_friendly"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 3,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 21.2763, "lng": -157.8278},
        "description": "The most elegant outdoor bar in Hawaii, set in the gardens of the Halekulani Hotel under a 100-year-old kiawe tree. Former Miss Hawaii performs traditional hula at sunset while you sip their legendary mai tai. Named after the Earl Biggers mystery novel. Pure magic.",
    },
    {
        "id": "rest_012",
        "name": "Senia",
        "island": "oahu",
        "cuisine": "Contemporary Fine Dining",
        "tags": ["fine dining", "chinatown", "innovative", "tasting menu", "intimate", "award winning", "local ingredients"],
        "dietary_tags": ["vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.3066, "lng": -157.8607},
        "description": "Chefs Chris Kajioka and Anthony Rush's intimate restaurant in Chinatown is consistently Honolulu's most exciting table. A seasonal tasting menu that sources from Hawaii's best farmers and fishermen, executed with precision. Only 36 seats. Book well in advance.",
    },
    {
        "id": "rest_013",
        "name": "Koko Head Cafe",
        "island": "oahu",
        "cuisine": "Creative Brunch",
        "tags": ["brunch", "kaimuki", "creative", "eggs", "local ingredients", "weekend", "hip", "casual"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options", "gluten_free_options"],
        "occasion_tags": ["social", "family", "solo"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 7, "close": 14},
        "location": {"lat": 21.2845, "lng": -157.7882},
        "description": "Lee Anne Wong's Kaimuki brunch spot is the most creative breakfast restaurant in Hawaii. Kimchi fried rice benedict, shrimp and grits with lemongrass, and rotating specials that reinterpret classic brunch through a Pacific lens. Weekend waits are long — arrive early.",
    },
    {
        "id": "rest_014",
        "name": "MW Restaurant",
        "island": "oahu",
        "cuisine": "Modern Hawaiian Farm-to-Table",
        "tags": ["farm to table", "local ingredients", "modern hawaiian", "upscale", "downtown", "innovative", "james beard"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion", "social"],
        "price_range": 3,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.3042, "lng": -157.8576},
        "description": "Michelle Karr-Ueoka and Wade Ueoka's restaurant is one of Hawaii's most celebrated. Their approach: take classic Hawaii comfort food (loco moco, saimin, poke) and reimagine it with the finest local ingredients and French technique. The kalua pig tortellini is legendary.",
    },
    {
        "id": "rest_015",
        "name": "Giovanni's Shrimp Truck",
        "island": "oahu",
        "cuisine": "Garlic Shrimp Food Truck",
        "tags": ["food truck", "shrimp", "garlic", "north shore", "iconic", "outdoor", "oahu legend"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["adventurous_dining", "social", "family"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "adventurous",
        "cuisine_style": "fast_casual",
        "spice_level": 3,
        "open_hours": {"open": 10, "close": 18},
        "location": {"lat": 21.5771, "lng": -158.1057},
        "description": "The original North Shore shrimp truck since 1993, covered in decades of customer graffiti. Scampi-style butter garlic shrimp or hot and spicy — 12 shrimp over two scoops of rice. Eat at picnic tables under a banyan tree while watching the North Shore surf world go by.",
    },
    {
        "id": "rest_016",
        "name": "Matsumoto Shave Ice",
        "island": "oahu",
        "cuisine": "Hawaiian Shave Ice",
        "tags": ["shave ice", "north shore", "haleiwa", "iconic", "sweet", "family", "must-do"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["family", "quick_bite"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 8, "close": 18},
        "location": {"lat": 21.5926, "lng": -158.1039},
        "description": "The most famous shave ice shop in the world since 1951. Located in Haleiwa on Oahu's North Shore. Hundreds of flavors, add azuki beans and ice cream at the bottom. The line wraps around the block on weekends. As Hawaiian as it gets.",
    },
    {
        "id": "rest_017",
        "name": "Ono Seafood",
        "island": "oahu",
        "cuisine": "Traditional Poke",
        "tags": ["poke", "ahi", "local secret", "no frills", "fresh", "honolulu", "authentic", "cash only"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "local",
        "spice_level": 2,
        "open_hours": {"open": 9, "close": 17},
        "location": {"lat": 21.2946, "lng": -157.8427},
        "description": "A tiny counter in a strip mall that is quietly one of the best poke shops in all of Hawaii. No elaborate Instagram-bowl presentations — just pristine ahi, marlin, and octopus cut that morning and seasoned the traditional way. Order by the pound. Bring cash.",
    },
    {
        "id": "rest_018",
        "name": "Haleiwa Joe's",
        "island": "oahu",
        "cuisine": "Seafood and Steak",
        "tags": ["north shore", "haleiwa", "ocean views", "casual fine", "seafood", "steak", "sunset"],
        "dietary_tags": ["seafood_heavy", "meat_focused"],
        "occasion_tags": ["romantic", "social", "family"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "romantic",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.5929, "lng": -158.1084},
        "description": "A beloved North Shore institution with stunning views over the Anahulu River estuary. Seafood and steak with a strong local following. The fresh fish specials are excellent — whatever the boat brought in that morning. Relaxed, friendly, genuinely beautiful setting.",
    },
    {
        "id": "rest_019",
        "name": "Ted's Bakery",
        "island": "oahu",
        "cuisine": "North Shore Bakery",
        "tags": ["chocolate haupia pie", "north shore", "bakery", "local", "budget", "surfer food", "beach"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["quick_bite", "family"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 20},
        "location": {"lat": 21.6416, "lng": -158.0556},
        "description": "The chocolate haupia pie from Ted's Bakery is one of the iconic foods of Oahu. A two-layer pie — chocolate pudding on the bottom, coconut haupia on top, whipped cream over everything. Also makes plate lunches for the Sunset Beach surf crowd. A North Shore essential stop.",
    },
    {
        "id": "rest_020",
        "name": "Tanioka's Seafoods",
        "island": "oahu",
        "cuisine": "Poke and Plate Lunch",
        "tags": ["poke", "plate lunch", "waipahu", "local institution", "fresh fish", "affordable", "takeout"],
        "dietary_tags": ["seafood_heavy"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 2,
        "open_hours": {"open": 8, "close": 19},
        "location": {"lat": 21.3741, "lng": -158.0115},
        "description": "Waipahu's legendary seafood counter has been slicing fresh poke since the 1970s. The local poke connoisseurs' first choice: spicy ahi, shoyu poke, salmon poke, and a rotating lineup of fresh preparations. Also does plate lunches. Get there early — they sell out.",
    },
    {
        "id": "rest_021",
        "name": "Mud Hen Water",
        "island": "oahu",
        "cuisine": "Contemporary Hawaiian",
        "tags": ["kaimuki", "creative", "craft cocktails", "modern hawaiian", "local sourcing", "hip", "dinner"],
        "dietary_tags": ["vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["social", "romantic", "adventurous_dining"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.2840, "lng": -157.7905},
        "description": "Ed Kenney's Kaimuki restaurant takes the concept of hyperlocal sourcing seriously — most ingredients come from within a few miles. Creative small plates built around what's growing and swimming in Hawaii right now. The cocktail program uses only local spirits and ingredients.",
    },
    {
        "id": "rest_022",
        "name": "Ethel's Grill",
        "island": "oahu",
        "cuisine": "Local Japanese Diner",
        "tags": ["kalihi", "local secret", "cheap", "japanese", "breakfast", "simple", "no frills", "authentic"],
        "dietary_tags": ["meat_focused", "seafood_heavy"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 13},
        "location": {"lat": 21.3357, "lng": -157.8951},
        "description": "A tiny counter in Kalihi that serves the best gyu-don (beef bowl) and oyako-don (chicken and egg bowl) in Hawaii at prices that feel impossible. The line of local construction workers and office employees is there every morning. Cash only, closes early, changes nothing.",
    },

    # ═══════════════════════════════════════════════════════
    # MAUI — 22 restaurants (post-2023 fire, no Front Street)
    # ═══════════════════════════════════════════════════════

    {
        "id": "rest_023",
        "name": "Mama's Fish House",
        "island": "maui",
        "cuisine": "Hawaiian Seafood Fine Dining",
        "tags": ["iconic", "oceanfront", "romantic", "fresh fish", "paia", "local institution", "slow paced"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.9301, "lng": -156.3083},
        "description": "The most iconic restaurant in Maui's history. Perched on a rocky point in Paia, the daily menu lists the fisherman's name beside each catch. White tablecloths, coconut-encrusted fresh fish, and ocean views that stop time. Book weeks in advance. Worth every effort.",
    },
    {
        "id": "rest_024",
        "name": "Merriman's Maui",
        "island": "maui",
        "cuisine": "Hawaii Regional Fine Dining",
        "tags": ["farm to table", "oceanfront", "kapalua", "fine dining", "local sourcing", "romantic", "wine"],
        "dietary_tags": ["seafood_heavy", "vegetarian_friendly"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 21},
        "location": {"lat": 20.9993, "lng": -156.6797},
        "description": "Peter Merriman — the godfather of Hawaii Regional Cuisine — built his Kapalua Bay restaurant on one rule: 90% of ingredients come from local farms and fishermen. The result is food that genuinely tastes like Hawaii. Sunset views over the water, exceptional wine cellar.",
    },
    {
        "id": "rest_025",
        "name": "Cane & Canoe",
        "island": "maui",
        "cuisine": "Contemporary Hawaiian Fine Dining",
        "tags": ["montage kapalua", "resort", "oceanfront", "romantic", "fine dining", "sunset", "cocktails"],
        "dietary_tags": ["seafood_heavy", "vegetarian_friendly"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 20.9970, "lng": -156.6800},
        "description": "Set above the water at Montage Kapalua Bay with sweeping Pacific views. The best hotel restaurant on Maui — farm-driven ingredients from local purveyors prepared with genuine care. Arrive for sunset cocktails on the terrace, stay for dinner. The cocktail program is extraordinary.",
    },
    {
        "id": "rest_026",
        "name": "Morimoto Maui",
        "island": "maui",
        "cuisine": "Japanese Fine Dining",
        "tags": ["iron chef", "sushi", "omakase", "wailea", "oceanfront", "fine dining", "creative"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "international",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 20.6847, "lng": -156.4434},
        "description": "Iron Chef Masaharu Morimoto at the Andaz Maui at Wailea. Dramatic ocean panoramas, a stunning sushi bar, and dishes that reinterpret Japanese cuisine through a Hawaiian lens. The omakase is a serious commitment — serious in the best possible way.",
    },
    {
        "id": "rest_027",
        "name": "Lineage",
        "island": "maui",
        "cuisine": "Modern Filipino-Hawaiian",
        "tags": ["sheldon simeon", "wailea", "upscale", "creative", "filipino", "cocktails", "local"],
        "dietary_tags": ["meat_focused", "seafood_heavy"],
        "occasion_tags": ["romantic", "social", "adventurous_dining"],
        "price_range": 3,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 20.7645, "lng": -156.4432},
        "description": "Top Chef winner Sheldon Simeon's love letter to his Filipino-Hawaiian heritage. Garlic noodles with kalua pig, chicken adobo reimagined with local ingredients, and a tasting of the islands that tells Hawaii's multicultural story through food. One of Maui's most exciting restaurants.",
    },
    {
        "id": "rest_028",
        "name": "The Mill House",
        "island": "maui",
        "cuisine": "Upcountry Farm-to-Table",
        "tags": ["farm to table", "waikapu", "garden", "romantic", "upcountry", "scenic", "local sourcing"],
        "dietary_tags": ["vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion", "adventurous_dining"],
        "price_range": 3,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.8820, "lng": -156.5250},
        "description": "Set within the historic Waikapu Valley surrounded by a 270-acre working farm. Ingredients grow feet from your table — the chef walks the property each morning before writing the menu. Romantic garden lanai, mountain views, fishponds, and cocktails that use farm-grown botanicals.",
    },
    {
        "id": "rest_029",
        "name": "Monkeypod Kitchen",
        "island": "maui",
        "cuisine": "Farm-to-Table American",
        "tags": ["wailea", "craft beer", "farm to table", "pizza", "happy hour", "social", "lively"],
        "dietary_tags": ["vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["social", "family", "friends_group"],
        "price_range": 3,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 11, "close": 23},
        "location": {"lat": 20.7590, "lng": -156.4469},
        "description": "The social hub of Wailea. 36 rotating craft beers on tap, 20 wines by the glass, wood-fired pizzas, and a menu built on local farm relationships. The happy hour from 3-5:30pm is the best on the island. Open-air, always buzzing, reliably excellent.",
    },
    {
        "id": "rest_030",
        "name": "Sansei Seafood & Sushi Bar",
        "island": "maui",
        "cuisine": "Asian Fusion Sushi",
        "tags": ["sushi", "kihei", "creative rolls", "late night", "happy hour", "seafood", "social"],
        "dietary_tags": ["seafood_heavy"],
        "occasion_tags": ["social", "friends_group", "romantic"],
        "price_range": 3,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 23},
        "location": {"lat": 20.7284, "lng": -156.4484},
        "description": "D.K. Kodama's creative sushi is legendary on Maui. Panko-crusted ahi, mango crab salad rolls, and Japanese-inspired desserts push the boundaries of Pacific fusion. The late-night happy hour (10pm+) offers 25-50% off and draws a dedicated crowd of locals who know.",
    },
    {
        "id": "rest_031",
        "name": "Tin Roof",
        "island": "maui",
        "cuisine": "Modern Plate Lunch",
        "tags": ["sheldon simeon", "kahului", "plate lunch", "creative", "local", "cheap", "garlic fried rice"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["solo", "quick_bite", "family"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "local",
        "spice_level": 2,
        "open_hours": {"open": 9, "close": 14},
        "location": {"lat": 20.9023, "lng": -156.4256},
        "description": "Sheldon Simeon's casual daytime window in Kahului. Creative plate lunches that elevate Filipino-Hawaiian comfort food — the mochiko chicken, garlic fried rice, and poke bowls are the stuff of local legend. Cash strongly preferred. Always a line. Always worth it. Closes at 2pm.",
    },
    {
        "id": "rest_032",
        "name": "Da Kitchen",
        "island": "maui",
        "cuisine": "Hawaiian Plate Lunch",
        "tags": ["plate lunch", "generous portions", "cheap", "loco moco", "kalua pig", "local", "comfort food"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["family", "solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 21},
        "location": {"lat": 20.8882, "lng": -156.4972},
        "description": "Two scoops of white rice, a generous scoop of mac salad, and your protein — this is the Hawaiian plate lunch in its purest form. Da Kitchen's loco moco (rice, hamburger patty, egg, gravy) is the one to order. Enormous portions, rock-bottom prices, deeply local.",
    },
    {
        "id": "rest_033",
        "name": "Paia Fish Market",
        "island": "maui",
        "cuisine": "Casual Seafood",
        "tags": ["fish tacos", "poke", "counter service", "paia", "fresh fish", "casual", "local"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["social", "solo", "family"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fast_casual",
        "spice_level": 2,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.9160, "lng": -156.3724},
        "description": "Counter-service in the heart of Paia town. The freshest fish tacos on Maui — blackened mahi, grilled ono, seared ahi — in thick flour tortillas with housemade slaw and salsa. Get a table on the patio and watch the surf crowd cycle through. No frills, maximum freshness.",
    },
    {
        "id": "rest_034",
        "name": "Leoda's Kitchen & Pie Shop",
        "island": "maui",
        "cuisine": "Comfort Food and Pies",
        "tags": ["banana cream pie", "comfort food", "olowalu", "roadside", "local", "breakfast", "bakery"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["family", "solo", "quick_bite"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 21},
        "location": {"lat": 20.8601, "lng": -156.6406},
        "description": "A roadside bakery in Olowalu between Lahaina and Kihei. The banana cream pie and haupia pie are the reason people drive the Honoapiilani Highway. The sweet potato bread is extraordinary. Generous plate lunches for the road. Stop here on any drive across the island.",
    },
    {
        "id": "rest_035",
        "name": "Ululani's Hawaiian Shave Ice",
        "island": "maui",
        "cuisine": "Hawaiian Shave Ice",
        "tags": ["shave ice", "award winning", "sweet", "family", "local", "tropical flavors", "refreshing"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["family", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 20},
        "location": {"lat": 20.8895, "lng": -156.5019},
        "description": "Multiple times named best shave ice in Maui and among the best in Hawaii. Ultra-fine Japanese-style ice machine, all-natural housemade syrups, and optional add-ons of azuki beans and condensed milk snow cap. Flavors like lilikoi, Kula strawberry, and lychee are transcendent.",
    },
    {
        "id": "rest_036",
        "name": "T. Komoda Store & Bakery",
        "island": "maui",
        "cuisine": "Century-Old Hawaiian Bakery",
        "tags": ["malasadas", "cream puffs", "makawao", "historic", "family owned", "early morning", "iconic"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 1,
        "noise_level": 1,
        "vibe": "solo",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 14},
        "location": {"lat": 20.8567, "lng": -156.3194},
        "description": "A family bakery in upcountry Makawao operating since 1916. The malasadas and cream puffs sell out before 10am most days. No website. No social media. The same recipes for over 100 years. Arrive early or the glass case will be empty. One of Hawaii's most genuine experiences.",
    },
    {
        "id": "rest_037",
        "name": "Kula Bistro",
        "island": "maui",
        "cuisine": "Italian-American",
        "tags": ["italian", "upcountry", "cozy", "pasta", "wood-fired pizza", "romantic", "local ingredients"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["romantic", "family"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "international",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.7910, "lng": -156.3470},
        "description": "A cozy Italian bistro at 3,000 feet in Kula where the air is cool and the pizza oven is always on. Upcountry-grown vegetables on handmade pasta and wood-fired pies. The mountain air at this elevation makes everything taste better. Genuinely romantic, genuinely relaxed.",
    },
    {
        "id": "rest_038",
        "name": "Noodle Boat Thai",
        "island": "maui",
        "cuisine": "Authentic Thai",
        "tags": ["thai", "spicy", "kihei", "authentic", "boat noodles", "curry", "local favorite"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["social", "solo"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "international",
        "spice_level": 3,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.7283, "lng": -156.4541},
        "description": "The most authentic Thai kitchen in Maui, run by a chef who grew up cooking in Bangkok. Boat noodles, green papaya salad, and massaman curry that comes with a real heat warning. Specify your spice level honestly — they take it seriously. Almost no tourists know about this place.",
    },
    {
        "id": "rest_039",
        "name": "Coconut's Fish Cafe",
        "island": "maui",
        "cuisine": "Casual Hawaiian Seafood",
        "tags": ["fish tacos", "poke", "local favorite", "kihei", "counter service", "fresh fish", "affordable"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["social", "family", "quick_bite"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fast_casual",
        "spice_level": 2,
        "open_hours": {"open": 10, "close": 21},
        "location": {"lat": 20.7571, "lng": -156.4451},
        "description": "Voted best fish tacos in South Maui year after year by people who eat fish tacos every day. Counter service with fresh mahi, ono, and ahi rotating based on what came off the boat. The coconut shrimp is a legitimate addiction. Simple, honest, and exceptional.",
    },
    {
        "id": "rest_040",
        "name": "Fork & Salad",
        "island": "maui",
        "cuisine": "Healthy Bowls and Salads",
        "tags": ["healthy", "wailea", "salads", "bowls", "vegan", "quick", "local sourcing", "light"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options", "gluten_free_options"],
        "occasion_tags": ["solo", "quick_bite", "family"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 21},
        "location": {"lat": 20.7596, "lng": -156.4472},
        "description": "Clean, fast, and genuinely delicious build-your-own salad and grain bowl concept in Wailea. Every ingredient is locally sourced from Maui farms. Perfect for the health-conscious visitor or local who wants real food fast. Bright, welcoming, and always fresh.",
    },
    {
        "id": "rest_041",
        "name": "Cafe des Amis",
        "island": "maui",
        "cuisine": "French-Indian Fusion",
        "tags": ["crepes", "indian curry", "paia", "brunch", "eclectic", "vegetarian", "surfer vibe"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["social", "solo", "adventurous_dining"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 3,
        "open_hours": {"open": 8, "close": 21},
        "location": {"lat": 20.9143, "lng": -156.3699},
        "description": "The most delightfully unexpected restaurant on Maui: French crepes and Indian curries served together in a laid-back Paia storefront. The masala dosa is excellent. The banana Nutella crepe is irresponsible. The crowd is surfers, yogis, and people who appreciate the unexpected.",
    },
    {
        "id": "rest_042",
        "name": "Flatbread Company",
        "island": "maui",
        "cuisine": "Wood-Fired Pizza",
        "tags": ["pizza", "wood fired", "organic", "paia", "family", "community", "vegetarian friendly"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["family", "social"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "family",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.9138, "lng": -156.3705},
        "description": "Handcrafted flatbread pizzas in a clay wood-fired oven using organic ingredients sourced from local Maui farms. The Paia community has made this their living room for decades. Great for families, great for groups. They donate a percentage of profits to local causes every Tuesday.",
    },
    {
        "id": "rest_043",
        "name": "Hula Grill Kaanapali",
        "island": "maui",
        "cuisine": "Hawaiian Seafood Grill",
        "tags": ["beachfront", "kaanapali", "toes in sand", "live music", "sunset", "casual", "seafood"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "family", "social"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "romantic",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 22},
        "location": {"lat": 20.9241, "lng": -156.6946},
        "description": "Literally toes-in-sand dining on Kaanapali Beach. A thatched roof, live ukulele at sunset, and casual Hawaiian seafood with the Pacific right at your feet. The torch lighting ceremony happens right outside. One of the most genuinely lovely dinner settings in all of Hawaii.",
    },
    {
        "id": "rest_044",
        "name": "Maui Brewing Company",
        "island": "maui",
        "cuisine": "Craft Beer Taproom",
        "tags": ["craft beer", "kihei", "taproom", "loud", "burgers", "social", "local brewery"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["friends_group", "social"],
        "price_range": 2,
        "noise_level": 4,
        "vibe": "social",
        "cuisine_style": "fast_casual",
        "spice_level": 2,
        "open_hours": {"open": 11, "close": 23},
        "location": {"lat": 20.7604, "lng": -156.4427},
        "description": "Maui's largest craft brewery with a massive open-air taproom and 24 beers on tap. The Coconut Porter and Big Swell IPA are Hawaii classics. Loaded burgers, nachos, and wings to soak it all up. Loud, fun, and the best place to watch a game or catch live music on Maui.",
    },

    # ═══════════════════════════════════════════════════════
    # BIG ISLAND — 14 restaurants
    # ═══════════════════════════════════════════════════════

    {
        "id": "rest_045",
        "name": "Merriman's Waimea",
        "island": "big_island",
        "cuisine": "Hawaii Regional Fine Dining",
        "tags": ["farm to table", "waimea", "original", "local sourcing", "romantic", "upcountry", "wine"],
        "dietary_tags": ["vegetarian_friendly", "seafood_heavy"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 3,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 21},
        "location": {"lat": 20.0171, "lng": -155.6709},
        "description": "Where Hawaii Regional Cuisine was born in 1988. Chef Peter Merriman's original restaurant in the cool ranching town of Waimea sources directly from the farms visible from the dining room window. The wok-charred ahi with local vegetables is a dish that changed Hawaiian cooking forever.",
    },
    {
        "id": "rest_046",
        "name": "Brown's Beach House",
        "island": "big_island",
        "cuisine": "Contemporary Fine Dining",
        "tags": ["mauna lani", "resort", "beachfront", "romantic", "fine dining", "sunset", "seafood"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 21},
        "location": {"lat": 19.9310, "lng": -155.8834},
        "description": "The most romantic restaurant on the Big Island, set at the edge of a protected cove at the Mauna Lani resort. Torch-lit, open-air dining with the sound of the Pacific and exceptional seafood caught locally. The ahi poke starter and fresh catch specials are always the move.",
    },
    {
        "id": "rest_047",
        "name": "Cafe Pesto",
        "island": "big_island",
        "cuisine": "Italian-Pacific Fusion",
        "tags": ["hilo", "pizza", "pasta", "creative", "casual fine", "historic building", "italian"],
        "dietary_tags": ["vegetarian_friendly", "seafood_heavy"],
        "occasion_tags": ["social", "family", "romantic"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 19.7266, "lng": -155.0888},
        "description": "In a beautifully restored 1912 building on Hilo Bay. Italian-Pacific fusion pizzas (fresh local herbs, Big Island goat cheese, artisan toppings), creative pasta, and spectacular bay views. A true Hilo institution that manages to feel both elegant and completely relaxed.",
    },
    {
        "id": "rest_048",
        "name": "Jackie Rey's Ohana Grill",
        "island": "big_island",
        "cuisine": "Modern American Hawaiian",
        "tags": ["kailua-kona", "local favorite", "seafood", "casual fine", "happy hour", "family", "fresh fish"],
        "dietary_tags": ["seafood_heavy", "meat_focused"],
        "occasion_tags": ["family", "social", "romantic"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 22},
        "location": {"lat": 19.6428, "lng": -155.9970},
        "description": "A Kailua-Kona institution beloved by locals and visitors equally. Fresh Big Island fish specials daily, creative salads, and comforting classics. The happy hour is the most popular in Kona. The staff has been there for years and it shows in every interaction.",
    },
    {
        "id": "rest_049",
        "name": "Island Lava Java",
        "island": "big_island",
        "cuisine": "Casual Breakfast and Coffee",
        "tags": ["kailua-kona", "coffee", "oceanfront", "breakfast", "brunch", "casual", "local"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 21},
        "location": {"lat": 19.6430, "lng": -155.9966},
        "description": "Right on Ali'i Drive with an open-air oceanfront patio that can't be beaten for breakfast. Big Island coffee (grown minutes away on the slopes of Hualalai), acai bowls, eggs benedict, and smoothies. The most pleasant way to start a morning in Kona.",
    },
    {
        "id": "rest_050",
        "name": "Tex Drive-In",
        "island": "big_island",
        "cuisine": "Malasadas and Plate Lunch",
        "tags": ["malasadas", "honokaa", "hamakua coast", "roadside", "cheap", "local", "road to hilo"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["quick_bite", "family"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 6, "close": 20},
        "location": {"lat": 20.0778, "lng": -155.4699},
        "description": "A drive-in on the Hamakua Coast in Honokaa that has been making malasadas since the 1960s. Made-to-order, piping hot, rolled in sugar. Filled versions are available. The stop everyone makes when driving the Hamakua Heritage Corridor from Waimea to Hilo.",
    },
    {
        "id": "rest_051",
        "name": "Kenichi Pacific",
        "island": "big_island",
        "cuisine": "Japanese Sushi and Pan-Asian",
        "tags": ["kailua-kona", "sushi", "japanese", "upscale", "creative rolls", "cocktails", "social"],
        "dietary_tags": ["seafood_heavy"],
        "occasion_tags": ["romantic", "social", "friends_group"],
        "price_range": 3,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 19.6440, "lng": -155.9966},
        "description": "Kona's best sushi bar with creative rolls that use Big Island fish alongside classic Japanese preparations. The dining room is sleek and intimate, the sake list is impressive, and the cocktails are inventive. A proper upscale night out in Kailua-Kona.",
    },
    {
        "id": "rest_052",
        "name": "Bamboo Restaurant",
        "island": "big_island",
        "cuisine": "Pacific Rim in Historic Building",
        "tags": ["hawi", "north kohala", "historic", "plantation era", "pacific rim", "cocktails", "artsy"],
        "dietary_tags": ["vegetarian_friendly", "seafood_heavy"],
        "occasion_tags": ["adventurous_dining", "romantic", "social"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "adventurous",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 20.2415, "lng": -155.8360},
        "description": "In a beautifully restored 1920s plantation-era building in the remote North Kohala town of Hawi. Colorful Pacific Rim cuisine, strong cocktails, and live Hawaiian music on weekends. Getting here requires a scenic drive through Kohala's rolling ranchlands — part of the experience.",
    },
    {
        "id": "rest_053",
        "name": "Umekes Fish Market Bar and Grill",
        "island": "big_island",
        "cuisine": "Poke and Hawaiian Seafood",
        "tags": ["poke", "kailua-kona", "fresh fish", "casual", "local", "acai", "affordable"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["solo", "family", "quick_bite"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "local",
        "spice_level": 2,
        "open_hours": {"open": 10, "close": 21},
        "location": {"lat": 19.6393, "lng": -155.9931},
        "description": "The best poke on the Big Island according to nearly everyone who lives there. Fresh fish sourced directly from local boats, cut each morning, and seasoned in the traditional Hawaiian way. The spicy ahi and the classic shoyu ahi are both exceptional. Get there before it sells out.",
    },
    {
        "id": "rest_054",
        "name": "Big Island Brewhaus",
        "island": "big_island",
        "cuisine": "Craft Beer and American",
        "tags": ["craft beer", "waimea", "upcountry", "social", "pub food", "local brewery", "views"],
        "dietary_tags": ["vegetarian_friendly"],
        "occasion_tags": ["social", "friends_group"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fast_casual",
        "spice_level": 2,
        "open_hours": {"open": 11, "close": 22},
        "location": {"lat": 20.0165, "lng": -155.6680},
        "description": "A craft brewery in the cool upcountry ranching town of Waimea, with views of Mauna Kea on clear days. The White Mountain Porter and Overboard IPA are standouts. Hearty pub food including a genuinely excellent burger made with Big Island Beef. Local crowd, relaxed energy.",
    },
    {
        "id": "rest_055",
        "name": "Hilo Bay Cafe",
        "island": "big_island",
        "cuisine": "Local Farm-to-Table",
        "tags": ["hilo", "farm to table", "bay views", "local", "casual fine", "breakfast", "lunch"],
        "dietary_tags": ["vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["solo", "social", "romantic"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 21},
        "location": {"lat": 19.7310, "lng": -155.0850},
        "description": "Overlooking Hilo Bay with a relaxed, neighborhood feel. Excellent local sourcing — Big Island farmers are listed on the menu by name. Breakfast is superb (the acai bowl uses real Big Island-grown acai). A local's everyday favorite that also impresses visitors every time.",
    },
    {
        "id": "rest_056",
        "name": "Nori's Saimin and Snacks",
        "island": "big_island",
        "cuisine": "Hawaiian Japanese Noodles",
        "tags": ["saimin", "hilo", "local institution", "cheap", "noodles", "japanese", "late night"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["solo", "quick_bite", "late_night"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "solo",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 23},
        "location": {"lat": 19.7220, "lng": -155.0812},
        "description": "Saimin is Hawaii's indigenous noodle soup — part ramen, part udon, part noodle soup history of the islands' plantation-era immigrants. Nori's in Hilo makes the definitive version: thin wheat noodles in a clear dashi broth with char siu, fish cake, and green onion. Essential.",
    },
    {
        "id": "rest_057",
        "name": "Quinn's Almost by the Sea",
        "island": "big_island",
        "cuisine": "Casual Bar and Grill",
        "tags": ["kailua-kona", "bar", "casual", "late night", "burgers", "local", "relaxed"],
        "dietary_tags": ["meat_focused", "seafood_heavy"],
        "occasion_tags": ["social", "friends_group", "late_night"],
        "price_range": 2,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 11, "close": 23},
        "location": {"lat": 19.6435, "lng": -155.9968},
        "description": "A no-pretension Kona bar and grill that has been the local fallback for decades. Cold beer, decent burgers, fresh fish, and an open-air setting that doesn't try to be anything it isn't. The kind of place you end up at when you stop looking for the perfect restaurant.",
    },
    {
        "id": "rest_058",
        "name": "KTA Super Stores Poke Counter",
        "island": "big_island",
        "cuisine": "Supermarket Poke",
        "tags": ["poke", "local secret", "supermarket", "cheap", "authentic", "fresh", "must-try"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "local",
        "spice_level": 2,
        "open_hours": {"open": 7, "close": 21},
        "location": {"lat": 19.7184, "lng": -155.0849},
        "description": "The open secret of Hawaii food culture: the best poke is often from the grocery store. KTA's fresh poke counter is cut daily from fish bought directly from local boats. Rotating 20+ preparations — classic shoyu, spicy mayo, island-style. Locals swear by it. Buy by the pound.",
    },

    # ═══════════════════════════════════════════════════════
    # KAUAI — 12 restaurants
    # ═══════════════════════════════════════════════════════

    {
        "id": "rest_059",
        "name": "The Beach House Restaurant",
        "island": "kauai",
        "cuisine": "Pacific Rim Seafood",
        "tags": ["poipu", "oceanfront", "romantic", "sunset", "fine dining", "seafood", "south shore"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 3,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.8703, "lng": -159.4654},
        "description": "The most coveted sunset table in Kauai — right on the water in Poipu, where spinner dolphins and green sea turtles often swim by during dinner. Pacific Rim seafood with a strong local sourcing philosophy. The deck faces due west. Book early and request a table outside.",
    },
    {
        "id": "rest_060",
        "name": "Bar Acuda",
        "island": "kauai",
        "cuisine": "Mediterranean Tapas",
        "tags": ["hanalei", "tapas", "wine", "mediterranean", "north shore", "intimate", "small plates"],
        "dietary_tags": ["vegetarian_friendly", "seafood_heavy"],
        "occasion_tags": ["romantic", "social", "adventurous_dining"],
        "price_range": 3,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "international",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 22.2041, "lng": -159.5018},
        "description": "A Mediterranean-inspired tapas bar in Hanalei village on Kauai's lush north shore. Wood-fired small plates, charcuterie, fresh local fish prepared simply, and an exceptional wine list. The intimate setting and quality of sourcing make it one of the most sophisticated restaurants in all of Hawaii.",
    },
    {
        "id": "rest_061",
        "name": "Postcards Cafe",
        "island": "kauai",
        "cuisine": "Creative Vegetarian Seafood",
        "tags": ["hanalei", "vegetarian", "organic", "north shore", "intimate", "creative", "health focused"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options", "gluten_free_options", "seafood_heavy"],
        "occasion_tags": ["romantic", "adventurous_dining"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 21},
        "location": {"lat": 22.2043, "lng": -159.5012},
        "description": "In a charming 1929 cottage in Hanalei, Postcards serves creative organic cuisine focusing on vegetarian preparations and locally caught seafood. No red meat, no poultry — just vegetables, grains, and pristine fish treated with genuine care. Beloved by Kauai's health-conscious community.",
    },
    {
        "id": "rest_062",
        "name": "Duane's Ono Char-Burger",
        "island": "kauai",
        "cuisine": "Old-School Burger Stand",
        "tags": ["anahola", "burgers", "roadside", "local", "cheap", "classic", "east kauai"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["quick_bite", "family"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "family",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 18},
        "location": {"lat": 22.1464, "lng": -159.3212},
        "description": "A roadside burger stand in Anahola that has barely changed since the 1970s. Char-broiled burgers with homemade sauces, teriyaki sauce, and a mushroom swiss that locals drive across the island for. The kind of roadside institution that every Hawaiian community has and protects fiercely.",
    },
    {
        "id": "rest_063",
        "name": "Hamura Saimin",
        "island": "kauai",
        "cuisine": "Traditional Hawaiian Saimin",
        "tags": ["saimin", "lihue", "local institution", "james beard", "cheap", "noodles", "authentic"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "solo",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 10, "close": 22},
        "location": {"lat": 21.9756, "lng": -159.3694},
        "description": "A James Beard American Classic Award winner in Lihue. Since 1952, this U-shaped counter has been serving Kauai's definitive saimin — the local noodle soup that blends Japanese, Chinese, Filipino, and Hawaiian plantation-era food traditions. The lilikoi chiffon pie for dessert is non-negotiable.",
    },
    {
        "id": "rest_064",
        "name": "Eating House 1849",
        "island": "kauai",
        "cuisine": "Hawaiian Regional",
        "tags": ["roy yamaguchi", "poipu", "creative", "local ingredients", "upscale casual", "social", "south shore"],
        "dietary_tags": ["seafood_heavy", "vegetarian_friendly"],
        "occasion_tags": ["social", "romantic", "special_occasion"],
        "price_range": 3,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 2,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.8888, "lng": -159.4720},
        "description": "Chef Roy Yamaguchi's Kauai concept in the Shops at Kukui'ula. Named after the year gold was discovered in California and Hawaiian provisions fed the miners, this is a creative exploration of Hawaiian food history. More relaxed than Roy's Honolulu but equally ambitious.",
    },
    {
        "id": "rest_065",
        "name": "Kilauea Fish Market",
        "island": "kauai",
        "cuisine": "Casual Poke and Fish Plates",
        "tags": ["kilauea", "poke", "fish plates", "north shore", "local", "cheap", "takeout"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "fast_casual",
        "spice_level": 2,
        "open_hours": {"open": 11, "close": 20},
        "location": {"lat": 22.2214, "lng": -159.4189},
        "description": "A small fish market and plate lunch counter in Kilauea town on Kauai's north shore. Fresh poke made daily, fish plates over rice, and homemade sauces. Order at the counter, take it to the nearby lighthouse or Kilauea Point for a picnic. Local knowledge, tourist-friendly prices.",
    },
    {
        "id": "rest_066",
        "name": "Red Salt",
        "island": "kauai",
        "cuisine": "Contemporary Fine Dining",
        "tags": ["poipu", "koa kea hotel", "fine dining", "oceanfront", "romantic", "seafood", "intimate"],
        "dietary_tags": ["seafood_heavy", "gluten_free_options"],
        "occasion_tags": ["romantic", "special_occasion"],
        "price_range": 4,
        "noise_level": 1,
        "vibe": "romantic",
        "cuisine_style": "fusion",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 22},
        "location": {"lat": 21.8706, "lng": -159.4660},
        "description": "The intimate restaurant inside the boutique Koa Kea Hotel in Poipu. Only 40 seats, each with an ocean view, and a menu focused on the finest local fish and produce. One of Kauai's quietest and most genuinely romantic dining experiences. The place to come when nothing else will do.",
    },
    {
        "id": "rest_067",
        "name": "Nourish Kauai",
        "island": "kauai",
        "cuisine": "Health Cafe and Smoothies",
        "tags": ["kapaa", "healthy", "acai", "vegan", "smoothies", "organic", "breakfast", "light"],
        "dietary_tags": ["vegan_options", "vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "solo",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 8, "close": 15},
        "location": {"lat": 22.0755, "lng": -159.3192},
        "description": "A bright, clean health cafe in Kapaa beloved by Kauai's health-conscious community. Organic acai bowls, cold-pressed juices from local fruits, nourish bowls packed with local greens and seeds. Everything plant-based, everything genuinely good. The morning crowd from the yoga community is regulars.",
    },
    {
        "id": "rest_068",
        "name": "Kauai Juice Co",
        "island": "kauai",
        "cuisine": "Cold-Pressed Juice and Wellness",
        "tags": ["juice", "healthy", "vegan", "coconut", "smoothies", "organic", "wellness", "north shore"],
        "dietary_tags": ["vegan_options", "vegetarian_friendly", "gluten_free_options"],
        "occasion_tags": ["solo", "quick_bite"],
        "price_range": 1,
        "noise_level": 1,
        "vibe": "solo",
        "cuisine_style": "fast_casual",
        "spice_level": 1,
        "open_hours": {"open": 7, "close": 17},
        "location": {"lat": 22.1991, "lng": -159.4979},
        "description": "Cold-pressed juices made from Kauai-grown tropical fruits — fresh sugarcane, turmeric, ginger, papaya, and seasonal specials from farms a few miles away. Multiple locations island-wide. The wellness ritual of Kauai locals who want something genuinely alive in a cup.",
    },
    {
        "id": "rest_069",
        "name": "Wrangler's Steakhouse",
        "island": "kauai",
        "cuisine": "Western Steakhouse",
        "tags": ["waimea", "steakhouse", "local beef", "western", "historic", "plantation era", "hearty"],
        "dietary_tags": ["meat_focused"],
        "occasion_tags": ["family", "social"],
        "price_range": 2,
        "noise_level": 2,
        "vibe": "family",
        "cuisine_style": "local",
        "spice_level": 1,
        "open_hours": {"open": 17, "close": 21},
        "location": {"lat": 21.9568, "lng": -159.6688},
        "description": "In the old sugar plantation town of Waimea near the Grand Canyon of the Pacific. A genuine cowboy steakhouse in a building that dates to the plantation era, serving locally-raised Kauai beef. The family-style service and history of the building make it one of Kauai's most distinctive experiences.",
    },
    {
        "id": "rest_070",
        "name": "Paco's Tacos Kauai",
        "island": "kauai",
        "cuisine": "Mexican-Hawaiian Fusion",
        "tags": ["tacos", "kapaa", "casual", "spicy", "fusion", "affordable", "fun", "social"],
        "dietary_tags": ["vegetarian_friendly", "vegan_options"],
        "occasion_tags": ["social", "friends_group", "quick_bite"],
        "price_range": 1,
        "noise_level": 3,
        "vibe": "social",
        "cuisine_style": "fusion",
        "spice_level": 3,
        "open_hours": {"open": 11, "close": 21},
        "location": {"lat": 22.0724, "lng": -159.3160},
        "description": "A casual taco spot in Kapaa that brings Mexican flavors to Hawaii with local ingredients — fresh mahi tacos, kalua pig burritos, and housemade salsas with Hawaiian chili peppers. Laid-back outdoor seating, strong margaritas, and the kind of energy that makes you order another round.",
    },
]
